/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-07-31 02:21:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.onLineTest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.vo.MemberVO;

public final class reGoTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/onLineTest/../common/JEasyUICommon.jsp", Long.valueOf(1564466243821L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.vo.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	//해당 사용자에 대한 정보는 로그인 할 때 세션으로 받으므로
	//해당세션을 받아 사용한다.
	//MemberCont에서 밑의 코드를 실행시켜줌
	//HttpSession session = req.getSession();
	MemberVO rmVO = (MemberVO) session.getAttribute("rmVO");
	String mem_id = rmVO.getMem_id();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>시험응시</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/icon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/demo/demo.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/commons.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.cookie.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar mem_id = '");
      out.print(mem_id);
      out.write("';\r\n");
      out.write("\t\tfunction examStart() {\r\n");
      out.write("\t\t\tvar examno = $(\"#tb_examno\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\tmethod : \"GET\"\r\n");
      out.write("\t\t\t\t,url : \"/onLineTest/isOk.kos?work=onLineTest&mem_id=\"+mem_id+\"&exam_no=\"+examno\r\n");
      out.write("\t\t\t\t,success : function(result) {\r\n");
      out.write("\t\t\t\t\tif(result==\"승인\") {\r\n");
      out.write("\t\t\t\t\t\t//문제지 정보를 가져온다.\r\n");
      out.write("\t\t\t\t\t\t//그런데 페이지는 이미 서버에서 클라이언트로 다운로드가 된 상태이므로 새로운 요청을 하면 페이지가 변경되는 상황\r\n");
      out.write("\t\t\t\t\t\t//현재 페이지는 그대로 유지되면서 시험시작 버튼을 클릭했을 때 내용 정보만 가져와서 기존 페이지에\r\n");
      out.write("\t\t\t\t\t\t//끼워넣고 싶다면 AJAX를 사용할 것.\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\tmethod : \"GET\"\r\n");
      out.write("\t\t\t\t\t\t\t,url : \"/onLineTest/swDesignExam.kos?work=onLineTest&sub_cd=\"+g_subcd\r\n");
      out.write("\t\t\t\t\t\t\t,success : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#dlg_test1\").dialog('open');\r\n");
      out.write("\t\t\t\t\t\t\t\t// 자바스크립트 객체 배열\r\n");
      out.write("\t\t\t\t\t\t\t\tvar jsonDoc = JSON.parse(data);\r\n");
      out.write("\t\t\t\t\t\t\t\tif(jsonDoc.length>0) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar j=1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor(var i=0;i<jsonDoc.length;i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar v_test1 = \"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar f_test = \"f_test\"+i;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tv_test1+=\"<form id='f_test\"+j+\"'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tv_test1+=jsonDoc[i].D_NO+\". \"+jsonDoc[i].QUESTION+\"<br><br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tv_test1+=\"&nbsp;&nbsp;<input type='checkbox' name='cb' value='1' onChange='answer(0,\"+j+\")'>\"+jsonDoc[i].ANSWER1+\"<br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tv_test1+=\"&nbsp;&nbsp;<input type='checkbox' name='cb' value='2' onChange='answer(1,\"+j+\")'>\"+jsonDoc[i].ANSWER2+\"<br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tv_test1+=\"&nbsp;&nbsp;<input type='checkbox' name='cb' value='3' onChange='answer(2,\"+j+\")'>\"+jsonDoc[i].ANSWER3+\"<br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tv_test1+=\"&nbsp;&nbsp;<input type='checkbox' name='cb' value='4' onChange='answer(3,\"+j+\")'>\"+jsonDoc[i].ANSWER4+\"<br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tv_test1+=\"</form>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#d_test\"+j).html(v_test1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tj++\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}//////////end of inner success\t\r\n");
      out.write("\t\t\t\t\t\t});////////////end of inner ajax\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}/////////////////end of if(result=='승인')\r\n");
      out.write("\t\t\t\t\telse if(result==\"확인불가\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_isOk\").html(\"<font color='red'>수험번호를 확인하세요.</font>\");\r\n");
      out.write("\t\t\t\t\t\treturn; // 함수 탈출\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}/////////////////////end of otter success\r\n");
      out.write("\t\t\t});////////////////////////end of outter ajax\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//체크박스 선택된것 해제시켜주기 - 선택 유무 - 멀티 초이스 막기\r\n");
      out.write("\t\tfunction answer(p_dap, num) {\r\n");
      out.write("\t\t\tfor(var i=0;i<document.getElementById(\"f_test\"+num).cb.length;i++) {\r\n");
      out.write("\t\t\t\tif(p_dap==i) { //0이 아닐 경우 다 true\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"f_test\"+num).cb[i].checked=1;\r\n");
      out.write("\t\t\t\t\t//alert(\"내가 선택한 답 : \"+document.getElementById(\"f_test\"+num).cb[i].value);\r\n");
      out.write("\t\t\t\t\t//$.cookie(\"c_test\"+num, document.getElementById(\"f_test\"+num).cb[i].value);\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"f_test\"+num).cb[i].checked=0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction prev(p_mytest, p_prevtest) {\r\n");
      out.write("\t\t\t$(\"#\"+p_mytest).dialog('close');\r\n");
      out.write("\t\t\t$(\"#\"+p_prevtest).dialog('open');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction next(p_mytest, num) { // num = 1,2,3,4\r\n");
      out.write("\t\t\t//alert(p_mytest+\", \"+p_nexttest);\r\n");
      out.write("\t\t\tvar dap; //사용자가 선택한 답을 담기\r\n");
      out.write("\t\t\tif(p_mytest=='dlg_test'+num) {\r\n");
      out.write("\t\t\t\t// 선택한 답안지의 값을 담기\r\n");
      out.write("\t\t\t\tvar temp = 1; // 체크박스가 넘어갈 때 마다 1씩 증가하기\r\n");
      out.write("\t\t\t\tfor(var i=0;i<document.getElementById(\"f_test\"+num).cb.length;i++) {\r\n");
      out.write("\t\t\t\t\tif(document.getElementById(\"f_test\"+num).cb[i].checked==1) {\r\n");
      out.write("\t\t\t\t\t\tdap = temp;\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\ttemp = temp+1;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//alert(num+\"의 dap : \"+dap);\r\n");
      out.write("\t\t\t\t$.cookie(\"c_test\"+num, dap);\r\n");
      out.write("\t\t\t\t//alert(num+\"번째 쿠키의 값\"+$.cookie(\"c_test\"+num));\r\n");
      out.write("\t\t\t\t$(\"#dlg_test\"+num).dialog('close');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(num==4) {\r\n");
      out.write("\t\t\t\t\t//$(\"#dlg_confirm\").dialog('open');\r\n");
      out.write("\t\t\t\t\t//다이얼 로그 창을 새로운 페이지로 이관(examResult.jsp)\r\n");
      out.write("\t\t\t\t\tcmm_window_popup('examResult.jsp','700','400','examResult');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#dlg_test\"+(num+1)).dialog('open');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar g_subcd = null;\r\n");
      out.write("\t\t$(document).ready(function (){\r\n");
      out.write("\t\t\t$('#cb_subject').combobox({\r\n");
      out.write("\t\t\t    url:'subjectList.kos?work=onLineTest'\r\n");
      out.write("\t\t\t    ,valueField:'SUB_CD'\r\n");
      out.write("\t\t\t    ,textField:'SUB_NAME'\r\n");
      out.write("\t\t\t    ,prompt : '수험번호를 선택하세요.'\r\n");
      out.write("\t\t\t    ,panelHeight:'auto'\r\n");
      out.write("\t\t\t    ,editable:false\r\n");
      out.write("\t\t\t    ,onSelect:function(record) {\r\n");
      out.write("\t\t\t    \t//alert(record.SUB_NAME);\r\n");
      out.write("\t\t\t    \tg_subcd = record.SUB_CD;\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- ===================== 패널 =================== -->\t\r\n");
      out.write("\t<div class=\"easyui-panel\" title=\"Test Take\" style=\"width:100%;max-width:400px;padding:30px 30px\">\r\n");
      out.write("\t\t<div style=\"margin-bottom:20px\">\r\n");
      out.write("\t\t\t<select class=\"easyui-combobox\" id=\"cb_subject\" label=\"수험과목 :\" labelPosition=\"left\" style=\"width:100%;\">\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"margin-bottom:20px\">\r\n");
      out.write("\t\t\t<input class=\"easyui-textbox\" id= \"tb_examno\" label=\"수험번호\" labelPosition=\"left\" style=\"width:200px\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\" \r\n");
      out.write("\t\t\tstyle=\"width:100%;height:32px\" onclick=\"examStart()\">시험시작</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"d_isOk\" style=\"padding:5px;\" align=\"center\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- ======== 시험문제1 ======== -->\r\n");
      out.write("\t<div id=\"dlg_test1\" class=\"easyui-dialog\" title=\"소프트웨어 디자인 문제 : 1\" style=\"width:700px;height:300px;\"\r\n");
      out.write("        data-options=\"iconCls:'icon-save',resizable:true,modal:true,closed:true,footer:'#ft_test1'\">\r\n");
      out.write("        <div id=\"d_test1\" style=\"margin-bottom:10px;\">\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 푸터 -->\r\n");
      out.write("\t<div id=\"ft_test1\" style=\"padding:5px;\" align=\"right\">\r\n");
      out.write("\t\t<a href=\"javascript:next('dlg_test1', 1)\" class=\"easyui-linkbutton\">다음</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- ======== 시험문제2 ======== -->\r\n");
      out.write("\t<div id=\"dlg_test2\" class=\"easyui-dialog\" title=\"소프트웨어 디자인 문제 : 2\" style=\"width:700px;height:300px;\"\r\n");
      out.write("        data-options=\"iconCls:'icon-save',resizable:true,modal:true,closed:true,footer:'#ft_test2'\">\r\n");
      out.write("        <div id=\"d_test2\" style=\"margin-bottom:10px\">\r\n");
      out.write("        \t\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 푸터 -->\r\n");
      out.write("\t<div id=\"ft_test2\" style=\"padding:5px;\" align=\"right\">\r\n");
      out.write("\t\t<a href=\"javascript:prev('dlg_test2','dlg_test1')\" class=\"easyui-linkbutton\">이전</a>\r\n");
      out.write("\t\t<a href=\"javascript:next('dlg_test2', 2)\" class=\"easyui-linkbutton\">이후</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- ======== 시험문제3 ======== -->\r\n");
      out.write("\t<div id=\"dlg_test3\" class=\"easyui-dialog\" title=\"소프트웨어 디자인 문제 : 3\" style=\"width:700px;height:300px;\"\r\n");
      out.write("        data-options=\"iconCls:'icon-save',resizable:true,modal:true,closed:true,footer:'#ft_test3'\">\r\n");
      out.write("        <div id=\"d_test3\" style=\"margin-bottom:10px\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 푸터 -->\r\n");
      out.write("\t<div id=\"ft_test3\" style=\"padding:5px;\" align=\"right\">\r\n");
      out.write("\t\t<a href=\"javascript:prev('dlg_test3','dlg_test2')\" class=\"easyui-linkbutton\">이전</a>\r\n");
      out.write("\t\t<a href=\"javascript:next('dlg_test3', 3)\" class=\"easyui-linkbutton\">이후</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- ======== 시험문제4 ======== -->\r\n");
      out.write("\t<div id=\"dlg_test4\" class=\"easyui-dialog\" title=\"소프트웨어 디자인 문제 : 4\" style=\"width:700px;height:300px;\"\r\n");
      out.write("        data-options=\"iconCls:'icon-save',resizable:true,modal:true,closed:true,footer:'#ft_test4'\">\r\n");
      out.write("        <div id=\"d_test4\" style=\"margin-bottom:10px\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 푸터 -->\r\n");
      out.write("\t<div id=\"ft_test4\" style=\"padding:5px;\" align=\"right\">\r\n");
      out.write("\t\t<a href=\"javascript:prev('dlg_test4','dlg_test3')\" class=\"easyui-linkbutton\">이전</a>\r\n");
      out.write("\t\t<a href=\"javascript:next('dlg_test4',4)\" class=\"easyui-linkbutton\">이후</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
