/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-07-24 09:26:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch09;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String c_name = null;
	Cookie cookies[] = request.getCookies();
	for(int i=0;i<cookies.length;i++) {
		out.print("쿠키 정보 : "+cookies[i].getValue());
		if(cookies[i].getName().equals("c_name")) {
			c_name = cookies[i].getValue();
		}
	}
/* 	if(c_name==null) {
		response.sendRedirect("a.jsp");
	} */

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Add and Remove Layout - jQuery EasyUI Demo</title>\r\n");
      out.write("    <!-- \r\n");
      out.write("    easyui.css는 jeasyui가 제공하는 콤포넌트(예:datagrid,layout 등)에 \r\n");
      out.write("       디자인을 입힐 때 사용됨\r\n");
      out.write("     -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/default/easyui.css\">\r\n");
      out.write("\t<!-- icon.css는 아이콘 이미지 처리하는데 사용됨 -->   \r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/icon.css\">\r\n");
      out.write("    <!-- jeasyui 데모페이지에 사용되는 css임 -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/demo/demo.css\">\r\n");
      out.write("    <!-- jeasyui가 jquery기반이므로 호환성을 검증한 스크립트 코드만 따로 모아둠. -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js\"\r\n");
      out.write("    charset=\"utf-8\"></script>\r\n");
      out.write("    <!-- \r\n");
      out.write("    jeasyui가 jquery기반이므로 아래 파일을 import하기 전에 반드시 jquery.min.js\r\n");
      out.write("       가 import되어 있어야 함. 순서 반드시 지킬것. \r\n");
      out.write("     -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar db_name=\"김유신\";\r\n");
      out.write("\t\t//입력 다이얼로그 창의 툴바 버튼 저장 취소 add, cancel 함수 선언\r\n");
      out.write("\t\t//a태그로 해당 함수를 부르기 때문에 a태그에 따로 아이디값은 적어주지 않고\r\n");
      out.write("\t\t//add버튼을 눌렀을 때 해당되는 이벤트만 선언해준다.\r\n");
      out.write("\t\t//사용자가 입력한 정보를 서버로(Tomcat) 전송해야 함.\r\n");
      out.write("\t\t//get 인터셉트를 한다. 누가(브라우저) -> 서버로 요청이 전송되지 않음.\r\n");
      out.write("\t\t//한번요청된 페이지는 각 사용자 PC에 그 내용이 다운로드\r\n");
      out.write("\t\t//두번 째 페이지를 요청하면 서버에 전달한 다음 응답을 받아오는 것이 아니라\r\n");
      out.write("\t\t//사용자 PC에 있는 정보가 그대로 다시 출력된다.\r\n");
      out.write("\t\t//XX.html?123 -> 주소창에 다른글자를 한자로 붙이면 새로운 요청으로 인식\r\n");
      out.write("\t\t//클라이언트측에 다운로드(html,css,js) -> 실시간 업데이트가 되지 않는다\r\n");
      out.write("\t\t//<form>태그(->metod:get(default-인터셉트)|post, action:이 요청을 처리해줄 페이지)로 전송해야함 \r\n");
      out.write("\t\tfunction saverow(target) {\r\n");
      out.write("            alert(\"saverow 호출성공\"+target);\r\n");
      out.write("        }\r\n");
      out.write("        //파라미터는 th태그(로우에 대한 오브젝트 값-target)\r\n");
      out.write("        //리턴타입은 숫자타입이고 로우의 index값을 반환한다.\r\n");
      out.write("        function getRowIndex(target) {\r\n");
      out.write("\t\t\talert(\"getRowIndex 호출성공\"+target);\r\n");
      out.write("            var tr = $(target).closest('tr.datagrid-row');\r\n");
      out.write("            return parseInt(tr.attr('datagrid-row-index'));\r\n");
      out.write("        }\r\n");
      out.write("        function cancelrow(target) {\r\n");
      out.write("            //alert(\"cancelrow 호출성공\"+target);\r\n");
      out.write("            $(\"#dg_emp\").datagrid('cancelEdit',getRowIndex(target));\r\n");
      out.write("        }\r\n");
      out.write("        function editrow(target) {\r\n");
      out.write("            alert(\"editrow 호출성공\"+target);\r\n");
      out.write("            $(\"#dg_emp\").datagrid(\"beginEdit\",getRowIndex(target));\r\n");
      out.write("        }\r\n");
      out.write("        function deleterow(target) {\r\n");
      out.write("            alert(\"deleterow 호출성공\"+target);\r\n");
      out.write("            $.messager.confirm('Confirm', '정말 삭제하시겠습니까?', function(r) {\r\n");
      out.write("                if(r) {\r\n");
      out.write("\t\t\t\t\tvar vdeptnos = \"\";//10,20,30\r\n");
      out.write("\t\t\t\t\tvar deptnoArr=[];//배열 선언\r\n");
      out.write("                    //datagrid 생성자 안에 {}는 필요없다\r\n");
      out.write("                    //why - 실행문이 필요 하지 않으므로\r\n");
      out.write("                    var rows = $(\"#dg_emp\").datagrid('getSelections');//속성 뒤에 -s가 있으면 배열이나 복수형\r\n");
      out.write("                    if(rows==null) {\r\n");
      out.write("                        alert(\"삭제할 사원을 선택하세요.\");\r\n");
      out.write("                        return;//deleterow함수를 탈출\r\n");
      out.write("                    }\r\n");
      out.write("\t\t\t\t\t//DELETE FROM emp WHERE deptno IN(10,20,30);\r\n");
      out.write("                    for(var i=0;i<rows.length;i++) {\r\n");
      out.write("                        //alert(rows[i].ename);\r\n");
      out.write("\t\t\t\t\t\tdeptnoArr.push(rows[i].deptno);//배열에 push(넣어주기)\r\n");
      out.write("                    }\r\n");
      out.write("                    for(var i=0;i<rows.length;i++) {\r\n");
      out.write("\t\t\t\t\t\tif(i==rows.length-1) {// 뒤에 콤마를 붙힐 필요가 없다.\r\n");
      out.write("\t\t\t\t\t\t\tvdeptnos+=deptnoArr[i];\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tvdeptnos+=deptnoArr[i]+\",\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("                    }\r\n");
      out.write("\t\t\t\t\tlocation.href=\"empDelete.jsp?deptnos=\"+vdeptnos;\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\t\tfunction add() {\r\n");
      out.write("\t\t\t$(\"#f_add\").submit();//폼태그의 액션 속성의 목적지로 간다.\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction cancel() {\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//수정 다이얼로그창 열기\r\n");
      out.write("\t\tfunction updForm() {\r\n");
      out.write("\t\t\tvar row = $(\"#dg_member\").datagrid(\"getSelected\");\r\n");
      out.write("\t\t\t//datagrid초기화 시 소문자로 작성하였으므로 반드시 소문자로 접근해야함.\r\n");
      out.write("\t\t\t//만일 대문자로 작성하면 undefine\r\n");
      out.write("\t\t\tvar c_id = row.id;\r\n");
      out.write("\t\t\t//alert(c_id);\r\n");
      out.write("\t\t\t//톰캣 서버로 이 아이디와 같은 상세정보를 조회하면 화면에 출력해야함,\r\n");
      out.write("\t\t\tlocation.href=\"./memberUpdateForm.jsp?id=\"+c_id;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//입력 다이얼로그창 열기\r\n");
      out.write("\t\tfunction addForm(){\r\n");
      out.write("\t\t\t$('#dlg_add').dialog('open');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//이름으로 검색학\r\n");
      out.write("\t\tfunction nameSearch() {\r\n");
      out.write("\t\t\talert(\"nameSearch호출성공\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//로그인 요청시 구현\r\n");
      out.write("\t\tfunction loginAction(){\r\n");
      out.write("            //front-end 언어는 오라클 서버와 연동할 수 없다. -- 상수처리한다.\r\n");
      out.write("            var db_id = \"test\";\r\n");
      out.write("            var db_pw = \"123\";\r\n");
      out.write("            var u_id = $(\"#tb_id\").val();\r\n");
      out.write("            var u_pw = $(\"#tb_pw\").val();\r\n");
      out.write("            if(db_id==u_id) {//아이디가 존재하니?\r\n");
      out.write("                if(db_pw==u_pw) { //비번까지 같은거야\r\n");
      out.write("                    //로그인폼 숨기고 대신 로그인 성공화면 show\r\n");
      out.write("                    $(\"#d_login\").hide();\r\n");
      out.write("                    $(\"#d_logout\").show();\r\n");
      out.write("                    //span태그에 메시지를 추가 - 김유신님 환영합니다.\r\n");
      out.write("                    $(\"#s_msg\").html(\"<b>\"+db_name+\"</b>님 환영합니다.\");\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(\"비밀번호가 맞지않습니다\");\r\n");
      out.write("                    $(\"#tb_pw\").textbox('setValue','');\r\n");
      out.write("                }\r\n");
      out.write("            } else {\r\n");
      out.write("                alert(\"해당 아이디가 존재하지 않습니다.\");\r\n");
      out.write("            }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//로그아웃 요청시 구현\r\n");
      out.write("\t\tfunction logoutAction(){\r\n");
      out.write("\t\t\t$(\"#d_logout\").hide();\r\n");
      out.write("\t\t\t$(\"#d_login\").show();\r\n");
      out.write("\t\t\t$(\"#tb_id\").textbox('setValue','');\r\n");
      out.write("\t\t\t$(\"#tb_pw\").textbox('setValue','');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//페이지네이션에서 페이지 이동 버튼을 클릭했을 때 오라클 서버에서 조회한 결과를 출력할것.\r\n");
      out.write("\t\tfunction pageMove(pageNumber, pageSize) {\r\n");
      out.write("\t\t\t//값을 두개 이상 보낼때는 & 연산자를 사용한다,\r\n");
      out.write("\t\t\t$(\"#dg_emp\").datagrid({\r\n");
      out.write("\t\t\t\t/* 화면에서 사용자가 보고자 하는 페이지에 대한 정보를 \r\n");
      out.write("\t\t\t\t   자바 코드에 전달(페이지수, 사용자가 보고싶은 페이지)해야 함.\r\n");
      out.write("\t\t\t\t   톰캣서버에게 전달 해야 한다. \r\n");
      out.write("\t\t\t\t   파라미터로 넘겨 받은 값을 활용하여 start값과 end값을 계산해야 함.\r\n");
      out.write("\t\t\t\t   start값 계산하기 \r\n");
      out.write("\t\t\t\t   -> start = ((page-1)*pageSize)+1\r\n");
      out.write("\t\t\t\t   end값 계산하기\r\n");
      out.write("\t\t\t\t   -> page*pageSize;\r\n");
      out.write("\t\t\t\t   if(end>total) {\r\n");
      out.write("\t\t\t\t\tend = total;\r\n");
      out.write("\t\t\t\t   } else {\r\n");
      out.write("\t\t\t\t\tend = end;\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\t\t\t\tSELECT a.rno, a.emp_name\r\n");
      out.write("\t\t\t\t  FROM (SELECT ROWNUM rno, emp_name FROM temp) a\r\n");
      out.write("\t\t\t\t WHERE a.rno>=:s AND a.rno <=:e\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\turl : './getEmpList.jsp?pageNumber='+pageNumber+\"&pageSize=\"+pageSize\r\n");
      out.write("\t\t\t\t,onDblClickCell:function(index,field,value) {\r\n");
      out.write("\t\t\t\t\talert(\"index : \"+index+\", field : \"+field+\", value : \"+value)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t#d_login {\r\n");
      out.write("\t\t    /*border: 1px solid red;*/\r\n");
      out.write("\t\t\twidth: 190px;\r\n");
      out.write("\t\t\theight: 110px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t//날짜 검색기\r\n");
      out.write("\t\t//날짜 포멧 형식을 디폴트에서 사용자 정렬으로 변경하므로\r\n");
      out.write("\t\t//body태그 안에 해당 컴포넌트가 정의되기 전에 처리함.\r\n");
      out.write("\t\t$.fn.datebox.defaults.formatter = function(date){\r\n");
      out.write("\t\t\tvar y = date.getFullYear();\r\n");
      out.write("\t\t\tvar m = date.getMonth()+1;\r\n");
      out.write("\t\t\tvar d = date.getDate();\r\n");
      out.write("\t\t\treturn y+'-'+(m<10 ? \"0\"+m:m)+'-'+(d<10 ? \"0\"+d:d);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//datebox에 날짜 포멧을 적용함\r\n");
      out.write("\t\t$.fn.datebox.defaults.parser = function(s){\r\n");
      out.write("\t\t\tvar t = Date.parse(s);\r\n");
      out.write("\t\t\tif (!isNaN(t)){\r\n");
      out.write("\t\t\t\treturn new Date(t);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn new Date();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).ready(function (){\r\n");
      out.write("\t\t\t/* 사원관리에 필요한 데이터 그리드 추가 - 설정 */\r\n");
      out.write("\t\t\t$(\"#dg_emp\").datagrid({\r\n");
      out.write("\t\t\t\turl : 'jsonEmp.json'\r\n");
      out.write("\t\t\t\t,singleSelect : true\r\n");
      out.write("\t\t\t\t,toolbar : '#tbar_emp'\r\n");
      out.write("\t\t\t\t,method : 'get'\r\n");
      out.write("\t\t\t\t//datagrid의 url정보를 통해서 data가 성공적으로 load됬을 때\r\n");
      out.write("\t\t\t\t,onLoadSuccess:function(data) {\r\n");
      out.write("\t\t\t\t\t$(\"#pn_emp\").pagination({\r\n");
      out.write("\t\t\t\t\t\ttotal:data.total\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t,onEndEdit:function(index,row) {\r\n");
      out.write("                    var ed = $(this).datagrid('getEditor',{\r\n");
      out.write("                        index : index\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("                ,onBeforeEdit:function(index,row) {\r\n");
      out.write("                    row.editing = true;\r\n");
      out.write("                    $(this).datagrid('refreshRow',index);\r\n");
      out.write("                }\r\n");
      out.write("                ,onAfterEdit:function(index,row) {\r\n");
      out.write("                    row.editing = false;\r\n");
      out.write("                    $(this).datagrid('refreshRow',index);\r\n");
      out.write("                }\r\n");
      out.write("                ,onCancelEdit:function(index,row) {\r\n");
      out.write("                    row.editing = false;\r\n");
      out.write("                    $(this).datagrid('refreshRow',index);\r\n");
      out.write("                }\r\n");
      out.write("\t\t\t});////////////end of datagrid\r\n");
      out.write("\t\t\t// $(\"#dg_emp\").datagrid('getPager').pagination({\r\n");
      out.write("\t\t\t// \tlayout:['list','sep','first','prev','links','next','last','sep','refresh']\r\n");
      out.write("\t\t\t// });\r\n");
      out.write("\t\t\t////페이지네이션 태그로 추가\r\n");
      out.write("\t\t\t$(\"#pn_emp\").pagination({\r\n");
      out.write("\t\t\t\tpageList: [1,2,3]\r\n");
      out.write("\t\t\t\t,pageSize: 1\r\n");
      out.write("\t\t\t\t,showPageList:true\r\n");
      out.write("\t\t\t\t,showRefresh:false\r\n");
      out.write("\t\t\t\t,onSelectPage: function(pageNumber, pageSize){\r\n");
      out.write("\t\t\t\t\t//alert(pageNumber+\",\"+pageSize);\r\n");
      out.write("\t\t\t\t\tpageMove(pageNumber,pageSize);//DB경유해야함.\r\n");
      out.write("\t            }\r\n");
      out.write("\t\t\t\t//, displayMsg:''\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t/* 회원관리에 필요한 데이터 그리드 추가 - 설정 */\r\n");
      out.write("\t\t\t$(\"#dg_member\").datagrid({\r\n");
      out.write("\t\t\t\tcolumns:[[\r\n");
      out.write("\t\t\t\t\t{field:'id', title:'ID', width:100}//아이디\r\n");
      out.write("\t\t\t\t\t,{field:'name', title:'이름', width:120}//이름\r\n");
      out.write("\t\t\t\t\t,{field:'address', title:'주소', width:300}//주소\r\n");
      out.write("\t\t\t\t\t,{field:'hp', title:'핸드폰번호', width:140}//HP\r\n");
      out.write("\t\t\t\t]]\r\n");
      out.write("\t\t\t\t,singleSelect : true\r\n");
      out.write("\t\t\t\t,toolbar : '#tbar_member'\r\n");
      out.write("\t\t\t\t,url : './jsonMember.json'\r\n");
      out.write("\t\t\t});////////////end of datagrid\r\n");
      out.write("//세개 페이지(회원관리,DVD관리,대여관리) 숨김 처리하기\t\t\t\r\n");
      out.write("\t\t\t$(\"#d_member\").hide();\r\n");
      out.write("\t\t\t$(\"#d_emp\").hide();\r\n");
      out.write("\t\t\t$(\"#d_dvd\").hide();\r\n");
      out.write("            $(\"#d_rental\").hide();\r\n");
      out.write("            //로그인 성공했을 때 화면을 숨기자\r\n");
      out.write("            $(\"#d_logout\").hide()\t\t\r\n");
      out.write("//easyui에서 제공하는 tree객체에 onClick이벤트 처리하기 시작\t\t\t\r\n");
      out.write("\t\t\t$('#te_menu').tree({//따로 함수 선언하지 않고 즉시 처리\r\n");
      out.write("\t\t\t\t//파라미터로 넘어오는 node는 사용자가 선택한 엘리먼트 정보 가짐\r\n");
      out.write("\t\t\t\tonClick: function(node){//트리메뉴 선택했을때 이벤트 처리\r\n");
      out.write("\t\t\t\t\t//alert(node.text);  // alert node text property when clicked\r\n");
      out.write("\t\t\t\t\t//node.text하면 선택한 노드문자열 가져옴.\r\n");
      out.write("\t\t\t\t\tif(\"회원관리\"==node.text){//너 회원관리 누른거야?\r\n");
      out.write("\t\t\t\t\t\t//alert(\"11\");\r\n");
      out.write("\t\t\t\t\t//show메소드 호출하면 화면에 출력되고\r\n");
      out.write("\t\t\t\t\t//hide메소드 호출하면 화면에 숨김 처리됨.\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_member\").show();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_emp\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_dvd\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_rental\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(\"사원관리\"==node.text) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_member\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_emp\").show();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_dvd\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_rental\").hide();\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(\"DVD관리\"==node.text){\r\n");
      out.write("\t\t\t\t\t\t//alert(\"22\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_member\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_emp\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_dvd\").show();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_rental\").hide();\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(\"대여관리\"==node.text){\r\n");
      out.write("\t\t\t\t\t\t//alert(\"33\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_member\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_emp\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_dvd\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#d_rental\").show();\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});////////////end of tree\r\n");
      out.write("\t\t});////////////////end of ready : DOM구성이 완료되었을 때\r\n");
      out.write("\t</script>\r\n");
      out.write("    <div id=\"cc\" class=\"easyui-layout\" style=\"width:950px;height:550px;\">\r\n");
      out.write("        <div data-options=\"region:'west',split:true\" title=\"코딩놀이\" style=\"width:200px;\">\r\n");
      out.write("\t\t<!-- 여백을 주기 위해 -->\r\n");
      out.write("\t\t<div style=\"margin:20px 0;\"></div>\r\n");
      out.write("<!--============= 로그인 화면 처리 시작 =============-->\t\t\r\n");
      out.write("\t\t<div id=\"d_login\" align=\"center\">\r\n");
      out.write("\t\t\t<input id=\"tb_id\" name=\"mem_id\">\t\r\n");
      out.write("\t\t\t<div style=\"margin:5px 0; \"></div>\r\n");
      out.write("\t\t\t<input id=\"tb_pw\" name=\"mem_pw\">\r\n");
      out.write("\t\t\t<div style=\"margin:5px 0; \"></div>\r\n");
      out.write("\t\t\t<a href=\"javascript:loginAction()\" class=\"easyui-linkbutton\">로그인</a>\t\r\n");
      out.write("\t\t\t<a href=\"javascript:memberAction()\" class=\"easyui-linkbutton\">회원가입</a>\t\r\n");
      out.write("\t\t\t<div style=\"margin:10px 0; \"></div>\r\n");
      out.write("\t\t\t<!-- 네이버 아이디로 로그인 버튼 노출 영역 -->\r\n");
      out.write("\t\t\t<div id=\"naver_id_login\"></div>\r\n");
      out.write("\t\t\t<!-- 네아로 자바스크립트 -->\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t//로그인 성공 시 이동할 페이지\r\n");
      out.write("\t\t\t\tvar naver_id_login = new naver_id_login(\"9r4FNQcya1CRyE7XrYw6\", \"http://localhost:8000/ajax/login/dbLogin_ajax.html\");\r\n");
      out.write("\t\t\t\tvar state = naver_id_login.getUniqState();\r\n");
      out.write("\t\t\t\tnaver_id_login.setButton(\"green\", 3, 40);\r\n");
      out.write("\t\t\t\tnaver_id_login.setDomain(\"http://localhost:8000/easyui_layout/layout_1.html\");\r\n");
      out.write("\t\t\t\tnaver_id_login.setState(state);\r\n");
      out.write("\t\t\t\tnaver_id_login.setPopup();\r\n");
      out.write("\t\t\t\tnaver_id_login.init_naver_id_login();\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$('#tb_id').textbox({\r\n");
      out.write("\t\t\t    iconCls:'icon-man'\r\n");
      out.write("\t\t\t    ,iconAlign:'right'\r\n");
      out.write("\t\t\t    ,prompt : '아이디'\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t$('#tb_pw').textbox({\r\n");
      out.write("\t\t\t    iconCls:'icon-lock'\r\n");
      out.write("\t\t\t    ,iconAlign:'right'\r\n");
      out.write("\t\t\t    ,prompt : '비밀번호'\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t</script>\t\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("<!--============= 로그인 화면 처리 끝 =============-->\t\t\r\n");
      out.write("<!--============= 로그아웃 화면 처리 시작 =============-->\t\t\r\n");
      out.write("        <div id=\"d_logout\" align=\"center\">\r\n");
      out.write("            <span id=\"s_msg\">\r\n");
      out.write("            </span>\r\n");
      out.write("            <div style=\"margin:5px 0; \"></div>\r\n");
      out.write("\t\t\t<a href=\"javascript:logoutAction()\" class=\"easyui-linkbutton\">로그아웃</a>\t\r\n");
      out.write("\t\t\t<a href=\"javascript:memberUpdate()\" class=\"easyui-linkbutton\">정보수정</a>\r\n");
      out.write("        </div>\r\n");
      out.write("<!--============= 로그아웃 화면 처리 끝 =============-->\t\t\r\n");
      out.write("<!--============== 메뉴 트리 시작 =============--> \r\n");
      out.write("\t\t<div style=\"margin:50px 0; \"></div>\r\n");
      out.write("        <ul id=\"te_menu\" class=\"easyui-tree\">\r\n");
      out.write("\t        <li data-options=\"state:'closed'\">\r\n");
      out.write("\t\t\t\t<span>사원관리</span>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span>사원목록</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span>사원등록</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span>사원수정</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span>사원삭제</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li data-options=\"state:'closed'\">\r\n");
      out.write("\t            <span>회원관리</span>\r\n");
      out.write("\t            <ul>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>회원목록</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>회원등록</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>회원수정</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>회원삭제</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t        <li data-options=\"state:'closed'\">\r\n");
      out.write("\t            <span>DVD관리</span>\r\n");
      out.write("\t            <ul>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>DVD목록</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>DVD등록</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>DVD수정</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>DVD삭제</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li data-options=\"state:'closed'\">\r\n");
      out.write("\t            <span>대여관리</span>\r\n");
      out.write("\t            <ul>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>대여목록</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>대여등록</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>대여수정</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <span>대여삭제</span>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("<!--============== 메뉴 트리  끝 =============--> \r\n");
      out.write("        </div>\r\n");
      out.write("        <div data-options=\"region:'center',title:'DVD관리시스템'\">\r\n");
      out.write("\t\t<div style=\"margin:10px 0; \"></div>\r\n");
      out.write("\t\t<!-- \r\n");
      out.write("\t\t=============================================================================\r\n");
      out.write("\t\t\t\t\t    \t   사원 관리  페이지   구현\r\n");
      out.write("\t\t==============================================================================\r\n");
      out.write("\t\t -->\r\n");
      out.write("\t\t <!-- 사원 관리 -->\r\n");
      out.write("\t\t \t<div id=\"d_emp\">\r\n");
      out.write("\t\t\t\t사원\r\n");
      out.write("\t\t\t\t<div style=\"margin:10px 0; \"></div>\r\n");
      out.write("\t\t\t\t<table id=\"dg_emp\" class=\"easyui-datagrid\" title=\"사원목록\" width=\"700px\" height=\"450px\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'empno',width:80\">사원번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'deptno',width:100,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tformatter:function(value,row){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn row.deptno;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\teditor:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype:'combobox',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\toptions:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalueField:'deptno',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttextField:'dname',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmethod:'get',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\turl:'../easyui-datagrid/deptvo.json',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trequired:true\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\">부서명</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'hiredate',width:150,align:'right',editor:{type:'text',options:{precision:2}}\">입사날짜</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field:'ename',width:100,align:'right',editor:{type:'text'}\">사원명</th>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- easyui에서 이벤트 처리에 상태를 구분하기 위해 만든 컬럼 - DB에 있는 값이 아니다. -->\r\n");
      out.write("\t\t\t\t\t\t\t<th data-options=\"field: 'Action', width:100, align:'center',\r\n");
      out.write("\t\t\t\t\t\t\t\tformatter:function(value,row,index) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(row.editing) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar s = '<a href=# onclick=saverow(this)>Save</a>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar c = '<a href=# onclick=cancelrow(this)>Cancel</a>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn s+' '+c;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar e = '<a href=# onclick=editrow(this)>Edit</a>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar d = '<a href=# onclick=deleterow(this)>Delete</a>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn e+' '+d;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\">Action</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<table id=\"pn_emp\" class=\"easyui-pagination\" width=\"700px\" style=\"background:#efefef;border:1px solid #ccc;\">\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div id=\"tbar_emp\">\r\n");
      out.write("\t\t\t\t\t<table align=\"left\" width=\"800\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 조건검색 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 식별하기 쉽게 input 태그에 라벨 속성으로 처리하는 것이 아닌 라벨태그로 처리한다. -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>이름 : </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-searchbox\" data-options=\"prompt:'이름을 입력하세요.', searcher:nameSearch\" style=\"width:150px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>H.P : </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-maskedbox\" mask=\"999-9999-9999\" data-options=\"prompt:'휴대폰번호를 입력하세요.'\" style=\"width:140px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>생년월일 : </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-datebox\" style=\"width:140px\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- 툴바 버튼 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"padding:2px 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" plain=\"true\">조회</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\">입력</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-edit\" plain=\"true\">수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- ============== 사원관리 화면 툴바  끝 ================ -->\r\n");
      out.write("\t\t\t\t<!-- ============== 회원정보 등록 화면(dialog) 끝  ================ -->\r\n");
      out.write("\t\t\t\t<!-- ============== 회원정보 수정 화면(dialog) 시작  ================ -->\r\n");
      out.write("\t\t\t\t<!-- ============== 회원정보 수정 화면(dialog) 끝  ================ -->\r\n");
      out.write("\t\t\t\t<!-- ============== 회원정보 삭제 화면(dialog) 시작  ================ -->\r\n");
      out.write("\t\t\t\t<!-- ============== 회원정보 삭제 화면(dialog) 끝  ================ -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t <!-- 회원 관리 -->\r\n");
      out.write("\t\t    <div id=\"d_member\">\r\n");
      out.write("\t\t\t\t Home - 회원관리\r\n");
      out.write("\t\t\t\t<div style=\"margin:10px 0; \"></div>\r\n");
      out.write("\t\t\t\t<table id=\"dg_member\" class=\"easyui-datagrid\" title=\"회원목록\" width=\"700px\" height=\"450px\"></table> \r\n");
      out.write("\t\t\t\t<!-- ============== 회원관리 화면 툴바 시작 ================ -->\r\n");
      out.write("\t\t\t\t<div id=\"tbar_member\">\r\n");
      out.write("\t\t\t\t\t<table align=\"left\" width=\"800\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 조건검색 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 식별하기 쉽게 input 태그에 라벨 속성으로 처리하는 것이 아닌 라벨태그로 처리한다. -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>이름 : </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-searchbox\" data-options=\"prompt:'이름을 입력하세요.', searcher:nameSearch\" style=\"width:150px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>H.P : </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-maskedbox\" mask=\"999-9999-9999\" data-options=\"prompt:'휴대폰번호를 입력하세요.'\" style=\"width:140px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>생년월일 : </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"easyui-datebox\" style=\"width:140px\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- 툴바 버튼 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"padding:2px 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" plain=\"true\">조회</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:addForm()\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\">입력</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:updForm()\" class=\"easyui-linkbutton\" iconCls=\"icon-edit\" plain=\"true\">수정</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- ============== 회원관리 화면 툴바  끝 ================ -->\r\n");
      out.write("\t\t\t\t<!-- ============== 회원정보 등록 화면(dialog) 시작  ================ -->\r\n");
      out.write("\t\t\t\t<div id=\"dlg_add\" data-options=\"footer:'#tbar_add',modal:true,closed:true,cache:false\" \r\n");
      out.write("\t\t\t\tclass=\"easyui-dialog\" title=\"회원등록\" style=\"width:600px;height:350px;padding:10px\">\r\n");
      out.write("\t\t\t\t\t<form id=\"f_add\" method=\"get\" action=\"memberAdd.jsp\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label>ID&nbsp;&nbsp;</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" style=\"width:150px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label>이름&nbsp;&nbsp;</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" style=\"width:150px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label>주소&nbsp;&nbsp;</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" style=\"width:150px\"></td>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label>H.P&nbsp;&nbsp;</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" style=\"width:150px\"></td>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label>성별&nbsp;&nbsp;</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" style=\"width:150px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label >생일&nbsp;&nbsp;</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-datebox\" style=\"width:150px\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label>비고&nbsp;&nbsp;</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"easyui-textbox\" style=\"width:150px\"></td>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"tbar_add\" align=\"right\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:add()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\" plain=\"true\">저장</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:cancel()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" plain=\"true\">취소</a>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t<!-- ============== 회원정보 등록 화면(dialog) 끝  ================ -->\r\n");
      out.write("\t\t\t\t<!-- ============== 회원정보 수정 화면(dialog) 시작  ================ -->\r\n");
      out.write("\t\t\t\t<!-- ============== 회원정보 수정 화면(dialog) 끝  ================ -->\r\n");
      out.write("\t\t\t\t<!-- ============== 회원정보 삭제 화면(dialog) 시작  ================ -->\r\n");
      out.write("\t\t\t\t<!-- ============== 회원정보 삭제 화면(dialog) 끝  ================ -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<!-- \r\n");
      out.write("\t\t=============================================================================\r\n");
      out.write("\t\t\t\t\t\t    화원 관리  페이지  구현  끝\r\n");
      out.write("\t\t==============================================================================\r\n");
      out.write("\t\t -->\r\n");
      out.write("\t\t<!-- DVD관리 -->\r\n");
      out.write("\t\t     <div id=\"d_dvd\">DVD</div>   \r\n");
      out.write("\t\t<!-- 대여관리 -->        \r\n");
      out.write("\t\t     <div id=\"d_rental\">대여</div>   \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
